apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux
  namespace: cms-dev
  annotations:
    cluster: geddes
spec:
  interval: 1m
  timeout: 1m
  path: "./deploy/core-staging/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af
  targetNamespace: cms-dev
  postBuild:
    substitute:
      enable_ingresses: "false"
      namespace: "cms-dev"
      jupyterhub_db_pv_selector: ""
      jupyterhub_db_storage_class: "geddes-standard-singlenode"
      jupyterhub_enable_ingress: "true"
      jupyterhub_logout_redirect_url: "https://cmsdev.geddes.rcac.purdue.edu/hub"
      jupyterhub_oauth_callback_url: "https://cmsdev.geddes.rcac.purdue.edu/hub/oauth_callback"
      jupyterhub_host: "cmsdev.geddes.rcac.purdue.edu"
      af_shared_storage_size: "1Gi"
      multinode_storage_class: "geddes-standard-multinode"
      singlenode_storage_class: "geddes-standard-singlenode"
      x509_secret_name: "af-x509-proxy-dev"
  decryption:
    provider: sops
    secretRef:
      name: sops-age
