apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux-experimental
  namespace: cms
  annotations:
    cluster: geddes
spec:
  interval: 1m
  timeout: 1m
  path: "./deploy/experimental/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af-experimental
  targetNamespace: cms
  postBuild:
    substitute:
      enable_ingresses: "true"
      namespace: "cms"
      multinode_storage_class: "geddes-standard-multinode"
      singlenode_storage_class: "geddes-standard-singlenode"
      x509_secret_name: "af-x509-proxy"
  decryption:
    provider: sops
    secretRef:
      name: sops-age
