apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../../apps/dask-gateway/dask-gateway-k8s-interlink/helmrelease.yaml
  # - ../../apps/dask-gateway/dask-gateway-k8s-interlink/ingress.yaml

  - ../../apps/interlink/helmrelease.yaml
  - ../../apps/interlink/cache-pvc.yaml
  - ../../apps/interlink/gitrepo.yaml
  - ../../apps/interlink/helmrepo.yaml
  - ../../apps/interlink/rbac.yaml

  - ../../apps/monitoring/pyroscope/helmrelease.yaml
  # - ../../apps/monitoring/loki/helmrelease.yaml
  # - ../../apps/monitoring/alloy/helmrelease.yaml

  - ../../apps/servicex/helmrelease.yaml
  - ../../apps/servicex/gitrepo.yaml
  - ../../apps/servicex/helmrepo.yaml

  - ../../apps/sonic/helmrepo.yaml
  - ../../apps/sonic/gitrepo.yaml
  - ../../apps/sonic/supersonic/helmrelease.yaml
  - ../../apps/sonic/supersonic-interlink/helmrelease.yaml
  # - ../../apps/sonic/supersonic-dynamic/gitrepo.yaml
  # - ../../apps/sonic/supersonic-dynamic/helmrelease.yaml

  - ../../apps/sonic/prometheus-networkpolicy.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: dask-gateway-k8s-interlink-config
    files:
      - values.yaml=../../apps/dask-gateway/dask-gateway-k8s-interlink/values.yaml

  - name: interlink-config
    files:
      - values.yaml=../../apps/interlink/values.yaml

  - name: pyroscope-config
    files:
      - values.yaml=../../apps/monitoring/pyroscope/values.yaml

  - name: loki-config
    files:
      - values.yaml=../../apps/monitoring/loki/values.yaml

  - name: alloy-config
    files:
      - values.yaml=../../apps/monitoring/alloy/values.yaml

  - name: servicex-config
    files:
      - values.yaml=../../apps/servicex/values.yaml

  - name: supersonic-config
    files:
      - values.yaml=../../apps/sonic/supersonic/values.yaml

  - name: supersonic-interlink-config
    files:
      - values.yaml=../../apps/sonic/supersonic-interlink/values.yaml

  - name: supersonic-dynamic-config
    files:
      - values.yaml=../../apps/sonic/supersonic-dynamic/values.yaml
