apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../../apps/af-utils/conda-env-builder/cronjob.yaml
  # - ../../apps/af-utils/conda-env-builder/rbac.yaml
  - ../../apps/af-utils/update-knowledge/rbac.yaml
  - ../../apps/af-utils/update-knowledge/cronjob.yaml
  - ../../apps/af-utils/update-knowledge/secret.yaml

  - ../../apps/dask-gateway/dask-gateway-k8s-interlink/helmrelease.yaml
  - ../../apps/dask-gateway/dask-gateway-k8s-interlink/ingress.yaml

  - ../../apps/interlink/helmrelease.yaml
  - ../../apps/interlink/cache-pvc.yaml
  - ../../apps/interlink/gitrepo.yaml
  - ../../apps/interlink/helmrepo.yaml
  - ../../apps/interlink/rbac.yaml

  - ../../apps/monitoring/pyroscope/helmrelease.yaml
  - ../../apps/monitoring/loki/helmrelease.yaml
  - ../../apps/monitoring/alloy/helmrelease.yaml

  - ../../apps/servicex/helmrelease.yaml
  - ../../apps/servicex/gitrepo.yaml
  - ../../apps/servicex/helmrepo.yaml

  - ../../apps/sonic/helmrepo.yaml
  - ../../apps/sonic/gitrepo.yaml
  - ../../apps/sonic/supersonic/helmrelease.yaml
  # - ../../apps/sonic/supersonic-interlink/helmrelease.yaml
  - ../../apps/sonic/supersonic-dynamic/gitrepo.yaml
  - ../../apps/sonic/supersonic-dynamic/helmrelease.yaml
  - ../../apps/sonic/supersonic-2508-fastml/gitrepo.yaml
  - ../../apps/sonic/supersonic-2508-fastml/helmrelease.yaml
  - ../../apps/sonic/supersonic-2508-nvidia/gitrepo.yaml
  - ../../apps/sonic/supersonic-2508-nvidia/helmrelease.yaml

  - ../../apps/sonic/supersonic-alma9/helmrelease.yaml
  - ../../apps/sonic/prometheus-networkpolicy.yaml

  - ../../apps/a2rchi/helmrelease.yaml
  - ../../apps/a2rchi/secret-hf-token.yaml
  - ../../apps/a2rchi/secret-openai-api-key.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  # - name: conda-env-builder-scripts
  #   files:
  #     - ../../apps/af-utils/conda-env-builder/generate-conda-env-jobs.sh
  #     - ../../apps/af-utils/conda-env-builder/build-single-conda-env.sh
  #     - ../../apps/af-utils/conda-env-builder/sitecustomize.py

  - name: update-knowledge-script
    files:
      - ../../apps/af-utils/update-knowledge/update_knowledge.py

  - name: dask-gateway-k8s-interlink-config
    files:
      - values.yaml=../../apps/dask-gateway/dask-gateway-k8s-interlink/values.yaml

  - name: interlink-config
    files:
      - values.yaml=../../apps/interlink/values.yaml

  - name: pyroscope-config
    files:
      - values.yaml=../../apps/monitoring/pyroscope/values.yaml

  - name: loki-config
    files:
      - values.yaml=../../apps/monitoring/loki/values.yaml

  - name: alloy-config
    files:
      - values.yaml=../../apps/monitoring/alloy/values.yaml

  - name: servicex-config
    files:
      - values.yaml=../../apps/servicex/values.yaml

  - name: supersonic-config
    files:
      - values.yaml=../../apps/sonic/supersonic/values.yaml

  - name: supersonic-interlink-config
    files:
      - values.yaml=../../apps/sonic/supersonic-interlink/values.yaml

  - name: supersonic-dynamic-config
    files:
      - values.yaml=../../apps/sonic/supersonic-dynamic/values.yaml

  - name: supersonic-2508-fastml-config
    files:
      - values.yaml=../../apps/sonic/supersonic-2508-fastml/values.yaml
      - envoy-config.yaml=../../apps/sonic/supersonic-2508-fastml/envoy-config.yaml

  - name: supersonic-2508-nvidia-config
    files:
      - values.yaml=../../apps/sonic/supersonic-2508-nvidia/values.yaml
      - envoy-config.yaml=../../apps/sonic/supersonic-2508-nvidia/envoy-config.yaml

  - name: supersonic-alma9-config
    files:
      - values.yaml=../../apps/sonic/supersonic-alma9/values.yaml

  - name: a2rchi-config
    files:
      - values.yaml=../../apps/a2rchi/values.yaml
