[workspace]
authors = ["Dmitry Kondratyev"]
channels = ["conda-forge"]
name = "pixi-global"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
awkward = "2.8.10.*"
bokeh = "3.1.0.*"
# boost = "*"
cabinetry = "*"
ca-certificates = "*"
certifi = "*"
click = "*"
cms-combine = "==10.4.2"
coffea = "2025.12.0*"
correctionlib="*"
dask = "*"
dask-gateway = "*"
dask-histogram = "*"
dask-jobqueue = "*"
dask-memusage = "*"
dask-ml = "*"
dask-xgboost = "*"
distributed = "*"
eigen = "*"
fsspec-xrootd = "*"
gcc_linux-64 = "*"
graphviz = "*"
gpustat = "*"
gsl = "*"
gxx_linux-64 = "*"
h5py = "*"
hepdata-lib = "*"
hist = "*"
ipykernel = "*"
ipympl = "*"
ipywidgets = "*"
jupyter-sshd-proxy = "0.3.0.*"
libgcc-devel_linux-64 = "*"
libgcc-ng = "*"
libstdcxx-devel_linux-64 = "*"
libstdcxx-ng = "*"
lmfit = "*"
mamba = "*"
matplotlib = "*"
mimesis = "*"
mplhep = "*"
numba = "*"
numpy = "*"
omegaconf = "*"
openssl = "*"
openssh = "*"
optuna = "*"
pandas = "*"
pcre2 = "*"
pip = "*"
plotly = "*"
py-spy = "*"
pyarrow = "*"
pycurl = "*"
pydot = "*"
pyhf = "*"
pyjuliacall = "*"
pytest = "*"
python = "3.*"
python-graphviz = "*"
pytorch = "2.9.*"
rucio-clients = "*"
root = "6.36.*"
scikit-learn = "*"
scikit-optimize = "*"
scipy = "*"
setuptools = "*"
sysroot_linux-64 = "*"
tbb = "*"
torch-geometric = "*"
tqdm = "*"
uncertainties = "*"
uproot = "5.6.8.*"
vdt = "*"
vector = "*"
xgboost = "*"
xrootd = "*"
yaml = "*"

[system-requirements]
cuda = "12.4"

[pypi-dependencies]
cmsstyle = "*"
dbs3-client = "*"
phyprakit = "*"
rabbit-fit = { version = "*", extras = ["plotting"] }
scalpl = "*"
servicex = "==3.1.1"
tensorflow = { version = "==2.20.0", extras = ["and-cuda"] }
tensorflow-probability = "==0.25"
tf-keras = "==2.20.1"
xgbfir = "*"
roastcoffea = "*"
pyroscope-io = "*"

