name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Qwen3 32B
    provider: openai
    model: qwen3:32b
    roles:
      - chat
      - edit
      - apply
    apiBase: https://genai.rcac.purdue.edu/api/
    apiKey:
  - name: Qwen3 32B
    provider: openai
    model: qwen3:32b
    roles:
      - autocomplete
    apiBase: https://genai.rcac.purdue.edu/api/chat/
    apiKey:
    requestOptions:
      extraBodyProperties:
        think: false
